## For a list of some properties that can be overriden go to http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
## The definitive list of properties comes from searching the source code (including Spring source code) for @ConfigurationProperties and @Value annotations, as well as the occasional use of RelaxedEnvironment



####################################################################################
#
#
#     Default configuration applies to ALL PROFILES
#
#
####################################################################################


##########################################
# Tomcat config
##########################################
server:
  port: ${port:0}
  #Set to 12k to support large cookie headers
  tomcat.max-http-header-size: 12288
  tomcat.uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  main:
    show-banner: false
  jmx:
    default_domain: com.citrix.g2w.reporting.write

info:
  service:
    name: ${app.name}
    build:
      projectVersion: ${project.version}
      rpmBuild: ${rpm.build:unknown}

logging:
  file: g2wreportingwrite.log
  level:
    #com.netflix.discovery: OFF
    com: INFO
    org: INFO
    net: INFO

log:
  access:
    file:
      directory: logs

reporting:
  queues:
    readTimeout: 5000
    connectTimeout: 5000
    prefix: local.com.citrix.g2w.reporting.events.
    listener: reporting
    servers: ed1.queue1svc.qai.expertcity.com:80,ed1.queue2svc.qai.expertcity.com:80           
---
####################################################################################
#
#
#     ED profile
#
#
####################################################################################   
---   
spring:
  profiles: ED
  data:
    mongodb:
      hosts:
       - g2whandoutsed5.acad.expertcity.com
       - g2whandoutsed20.avad.expertcity.com
       - g2whandoutsed-mongo01.acad.expertcity.com
       - g2whandoutsed19.avad.expertcity.com
       - g2whandoutsed20.avad.expertcity.com
      port: 27017
      database: g2whandouts
      username: g2whandouts
      encrypted:
        password: lcmvGDlBDwhbvt6qAU9vMA==:9YVhTHt6ka39aNpqz6ttQLPxqsslhn0CgL1hV/mD9CVbasy0zfTtcZ09JWPGMp/f
####################################################################################
#
#
#     RC profile
#
#
####################################################################################
---
spring:
  profiles: RC
  data:
    mongodb:
      hosts:
       - g2whandoutsrc-mongom.acad.expertcity.com
      port: 27017
      database: g2whandouts
      username: g2whandouts
      encrypted:
        password: lcmvGDlBDwhbvt6qAU9vMA==:9YVhTHt6ka39aNpqz6ttQLPxqsslhn0CgL1hV/mD9CVbasy0zfTtcZ09JWPGMp/f
####################################################################################
#
#
#     STAGE profile
#
#
####################################################################################
---
spring:
  profiles: STAGE
  data:
    mongodb:
      hosts:
       - g2w-stage-mongo01.aca.expertcity.com
       - g2w-stage-mongo02.aca.expertcity.com
       - g2w-stage-mongo01.ava.expertcity.com
       - g2w-stage-mongo02.ava.expertcity.com
      port: 27017
      database: g2whandouts
      username: g2whandouts
      encrypted:
        password: CSxElwC1x6flVItbDyLAEw==:aa1dY3BkeHwsYi0bP51MurWJg9CmbjohwinTphkaIx2due9xtl3XY++gq+RU4wGX3Ds2cW1lz5PwCK2oiHoDvA==

####################################################################################
#
#
#     LIVE profile
#
#
####################################################################################
---
spring:
  profiles: LIVE
  data:
    mongodb:
      hosts:
       - g2w-mongo01.aca.expertcity.com
       - g2w-mongo02.aca.expertcity.com
       - g2w-mongo01.ava.expertcity.com
       - g2w-mongo02.ava.expertcity.com
      port: 27017
      database: g2whandouts
      username: g2whandouts
      encrypted:
        password: CSxElwC1x6flVItbDyLAEw==:aa1dY3BkeHwsYi0bP51MurWJg9CmbjohwinTphkaIx2due9xtl3XY++gq+RU4wGX3Ds2cW1lz5PwCK2oiHoDvA==
##########################################
# Microservice properties
##########################################
